#!/bin/sh

GREP='grep -n --color=auto'
ECHO='/bin/echo'
MEM='memoire'

$ECHO '===> devrait être \eqref <==='
$GREP '\\ref{e:' *.tex
$GREP '\\vref{e:' *.tex

$ECHO ""
$ECHO '===> devrait être \ref <==='
$GREP '\\eqref{[^e]:' *.tex

$ECHO ""
$ECHO '===> devrait être \vref ou \oref <==='
$GREP '\\ref{[^e]:' *.tex

$ECHO ""
$ECHO '===> doit disparaître <==='
$GREP -B2 '\\todo\|\\worknote\|XXX' *.tex

$ECHO ""
$ECHO "Making $MEM.pdf"
make $MEM.pdf >/dev/null 2>&1
pdftotext $MEM.pdf - | grep --color=auto '()'

$ECHO ""
texloganalyser -wou $MEM.log | sed 's/^\(\[[0-9]\+]\)*//' | \
    grep --color=auto '^.*\(box\|arning\)\>'
