% !TEX root = slides

% personal class for thesis slides [[2
%
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{mpg-thslides}

% use beamer with custom encoding, fonts and colors [[2
%
\LoadClass{beamer}
% add french to global options
\edef\@classoptionslist{\@classoptionslist,french}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[sc, osf]{mathpazo}
\usepackage{amssymb}
\renewcommand\sfdefault{iwona}
\rmfamily
\DeclareFontShape{T1}{pplj}{bx}{sc}{<->ssub*pplj/bx/n}{}

\definecolor{mstruct}{rgb}{0.7,0.0,0.0}

% beamer theme [[2
%
\usetheme[compress]{Singapore}
\usefonttheme[onlymath]{serif}
\usefonttheme{professionalfonts}
\setbeamercolor{structure}{fg=mstruct}
\setbeamertemplate{navigation symbols}{}
% pour avoir les vignettes de Singapore sans sous-sections
\setcounter{subsection}{1}
\usepackage{remreset}
\makeatletter \@removefromreset{subsection}{section} \makeatother

% load various useful packages [[2
%
\usepackage{mathtools, mathstyle}
\usepackage{ifmtarg, fixltx2e, xargs, xspace, cmdstring, ted, etex}
\usepackage{tikz}
\usetikzlibrary{arrows,positioning,fit,decorations.pathmorphing,shapes.misc}
\usepackage{babel}

% frenchb (+xspace) settings [[2
%
\frenchbsetup{og=«,fg=»,
  AutoSpacePunctuation=false,
  ThinColonSpace=true,
  SuppressWarning=true,
}

% nbsp treated as a normal space (to let frenchb do its job)
\DeclareUnicodeCharacter{00A0}{ }

% don't eat space before high punctuation
\xspaceremoveexception{:}
\xspaceremoveexception{;}
\xspaceremoveexception{?}
\xspaceremoveexception{!}

% theorems & Co [[2
%
\newtheorem{thm}{Théorème}
\newtheorem{prop}{Proposition}
\newtheorem{coro}{Corollaire}
\newtheorem{tdef}{Définition}
\let\fact\relax
\newtheorem{fact}{Fait}
\newtheorem{lem}{Lemme}

% numbering [[2
%
\mathtoolsset{showonlyrefs,showmanualtags}

% tocs [[2
%
\newcommand \tocsect {%
  %\frame{\tableofcontents[currentsection]}
}
\newcommand \toc {%
  \frame{\tableofcontents}
}


% input macros [[2
\input macros

% [[1
% vim: ft=tex fdm=marker fmr=[[,]] fdl=1 spell spelllang=fr,en
